spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      # database: ${REDIS_DATABASE:0} # 로컬에서만 Redis Cloud는 선택 불가
  jpa:
    hibernate:
      ddl-auto: validate

# Logging (파일 출력 + 롤링)
logging:
  level:
    root: INFO
    io.github.hgkimer.privateblog: INFO
    p6spy: OFF
  file:
    name: ./logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  cookie-name: ${JWT_COOKIE_NAME}
  refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME}
  use-secure-cookie: true # http: false / https: true


# p6spy 비활성화 (prod 환경)
decorator:
  datasource:
    p6spy:
      enable-logging: false