# nginx.config에 include 되어있음
map $request_uri $bad_word {
    default 0;

    # [Category: CMS & Framework Attacks]
    ~*(\.php|wp-includes|wlwmanifest|xmlrpc|wordpress|administrator|wp-admin|wp-login|owa|a2billing|magento|fckeditor|wp-content|wp-json|wp-plain) 1;

    # [Category: System & Panel Scans]
    ~*(fgt_lang|flu|stalker_portal|streaming|system_api|exporttool|ecp|vendor|LogService|invoke|phpinfo|console|sidekiq|c99|GponForm|telescope|actuator|configprops|monitoring|balancer) 1;

    # [Category: Info Leakage & Configuration]
    ~*(\.env|\.git|\.well-known|DS_Store|nginx|ads|humans|meta-data|web_shell_cmd|latest|remote|idx_config|Autodiscover|mifs|staging|demo|rss|root) 1;

    # [Category: Script & API Exploits]
    ~*(eval-stdin|exec|level|bash|Bind|binding|appxz|bankCheck|GetAllGameCategory|exchangerateuserconfig|exchange_article|kline_week|anquan|dns-query|nsepa_setup|java_script|gemini-iptv|j_spring_security_check|wps|cgi|asmx|HNAP1|sdk|evox|_ignition|alvzpxkr|ALFA_DATA) 1;

    # [Category: Critical Vulnerabilities (Log4j & Others)]
    ~*(ldap|jndi|dns|securityscan|rmi|ldaps|iiop|corba) 1;

    # [Category: Detected from your access.log]
    ~*(containers/json|xltt|pearcmd|md5|libredtail) 1;
}